name: flutter_complete_guide
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.0
  drag_and_drop_gridview:
  dotted_border: ^2.0.0+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_focus_watcher: ^2.0.0
  camera: ^0.8.1+7
  video_player: ^2.1.12
  flutter_launcher_icons: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/logo.png
     - assets/logo/logo.png
     - assets/logo/logo-outline.png
     - assets/logo/logo-title.png
     - assets/logo/cut-logo.png
     - assets/logo/logo-outline-title.png
     - assets/icons/open-book64.png
     - assets/icons/open-book128.png
     - assets/icons/process64.png
     - assets/icons/process128.png
     - assets/icons/camera64.png
     - assets/icons/camera128.png
     - assets/icons/settings.png
     - assets/icons/settings32.png
     - assets/icons/settings64.png
     - assets/icons/letter-x.png
     - assets/icons/back-purple32.png
     - assets/icons/left-arrow.png
     - assets/icons/right-arrow.png
     - assets/icons/plus64.png
     - assets/icons/glass64.png
     - assets/icons/glass128.png
     - assets/chords/A.png
     - assets/chords/A7.png
     - assets/chords/Ab.png
     - assets/chords/Am.png
     - assets/chords/B.png
     - assets/chords/B7.png
     - assets/chords/Bb.png
     - assets/chords/Bb7.png
     - assets/chords/Bbm.png
     - assets/chords/Bm.png
     - assets/chords/C.png
     - assets/chords/C#m.png
     - assets/chords/C7.png
     - assets/chords/Cm.png
     - assets/chords/D.png
     - assets/chords/D7.png
     - assets/chords/Db.png
     - assets/chords/Dm.png
     - assets/chords/E flat.png
     - assets/chords/E.png
     - assets/chords/E7.png
     - assets/chords/Eb7.png
     - assets/chords/Em.png
     - assets/chords/Empty diagram.png
     - assets/chords/F.png
     - assets/chords/F#.png
     - assets/chords/F#7.png
     - assets/chords/F#m.png
     - assets/chords/F7.png
     - assets/chords/Fm.png
     - assets/chords/G.png
     - assets/chords/G#m.png
     - assets/chords/G7.png
     - assets/chords/Gm.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: BankGothicLight
      fonts:
        - asset: fonts/bank-gothic-light-bt.ttf
    - family: BankGothicMedium
      fonts:
        - asset: fonts/bank-gothic-medium-bt.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
